In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

Data Generation
===

In [2]:
num_samples, num_features = 10, 5

In [3]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [4]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [11]:
def standardize(x):
    x = (x - np.mean(x))/np.std(x)
    return x
def standardize_v2(x):
    for ii in range(len(x)):
        x[ii] = (x[ii] - np.mean(x[ii]))/np.std(x[ii])
    return x

std_data = standardize(data)

In [12]:
std_data2 = standardize_v2(data)

In [13]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.86197913 -1.87116608  0.36065436  0.77998587 -0.13145328]
 [-0.26342346 -0.37455074  1.96352175 -0.49489884 -0.83064871]
 [ 0.27947082  1.09495185 -1.79369593 -0.24738438  0.66665763]
 [-0.19085472  0.3412883  -1.75299726  1.29625264  0.30631105]
 [ 0.60541755 -1.64438471 -0.34537934  1.34485005  0.03949646]
 [-1.63609033  0.68978992 -0.63456358  1.10281149  0.4780525 ]
 [ 0.91371769 -0.02446828  1.25589232 -0.69412718 -1.45101455]
 [-0.27538787 -0.89782305  1.48468977 -1.12146766  0.80998881]
 [-0.0283688   1.0306067  -1.38721538  1.17701266 -0.79203518]
 [ 0.95879913 -0.67226127  1.41854245 -0.56718345 -1.13789686]] 

 [ 0.12252591 -0.23280174  0.05694491  0.25758512 -0.20425421] 

 [0.75172764 0.9957692  1.35954267 0.91665941 0.75776425]


In [14]:
print(std_data2, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.86197913 -1.87116608  0.36065436  0.77998587 -0.13145328]
 [-0.26342346 -0.37455074  1.96352175 -0.49489884 -0.83064871]
 [ 0.27947082  1.09495185 -1.79369593 -0.24738438  0.66665763]
 [-0.19085472  0.3412883  -1.75299726  1.29625264  0.30631105]
 [ 0.60541755 -1.64438471 -0.34537934  1.34485005  0.03949646]
 [-1.63609033  0.68978992 -0.63456358  1.10281149  0.4780525 ]
 [ 0.91371769 -0.02446828  1.25589232 -0.69412718 -1.45101455]
 [-0.27538787 -0.89782305  1.48468977 -1.12146766  0.80998881]
 [-0.0283688   1.0306067  -1.38721538  1.17701266 -0.79203518]
 [ 0.95879913 -0.67226127  1.41854245 -0.56718345 -1.13789686]] 

 [ 0.12252591 -0.23280174  0.05694491  0.25758512 -0.20425421] 

 [0.75172764 0.9957692  1.35954267 0.91665941 0.75776425]
